version: '3'

services:
  speech:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: speech
    ports:
      - "8888:8888" # jupyter 1
      - "8889:8889" # jupyter 2
      - "6006:6006" # tensorboard 1
      - "6007:6007" # tensorboard 2
    deploy: # gpu
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/storage/:/mnt/storage/ # general storage
      - /var/www/html/ai/models/:/var/www/html/ai/models/ # repo models
    restart: no

