version: '3'

services:
  speech:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: speech
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/storage/:/mnt/storage/
    restart: no

